### ISSUE TITLE
Setup a Personal Cloud via Dockerfiles

### ISSUE THREAD

**Issue by indiv0** [indiv0/dockerfiles#5]
# Desired Machines

* [ ] SSH bastion host
    * Visible from outside of network
    * Allows SSH access
* [ ] Webserver
    * For my personal website
* [ ] Database
* [ ] Git repositories
* [ ] Authoritative DNS server (BIND9)
    * Resources
        * [sameersbn/docker-bind](https://github.com/sameersbn/docker-bind)
        * [jenkins-infra/bind](https://github.com/jenkins-infra/bind)
        * [Setting up a home DNS server with BIND9](http://www.reddit.com/r/HomeNetworking/comments/254tzi)
* [ ] Recursive DNS server (Unbound)
    * [ ] Load-balanced
    * [ ] Ensure DNS queries are forwarded here from the router
    * [ ] Ensure no DNS leaks
        * https://www.dnsleaktest.com/

# Tasks

* [ ] Automated backups of data, and configuration files
* [ ] Ensure DNSCrypt for both the authoritative and recursive nameserver
    * http://dnscrypt.org/
    * https://github.com/opendns/dnscrypt-proxy
* [ ] Tell my DHCP server to set the DHCP search domain to my local domain so that something like `lap01` resolves to `lap01.home.ternary.io`
